version: '3.4'

services:
  isi_data_insights:
    image: clamalfa/isi_data_insights
    configs:
      - source: isi_data_config
        target: /etc/data_insights/isi_data_insights_d.cfg
        mode: 444
    deploy:
      replicas: 1

  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=isi_data_insights
    deploy:
      replicas: 1

  grafana:
    image: clamalfa/idic_grafana
    networks:
      - traefik-net
      - default
    configs:
      - source: grafana_dashboards
        target: /etc/grafana/provisioning/dashboards/default.yml
        mode: 444
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/default.yml
        mode: 444
    environment:
      - GF_SERVER_ROOT_URL=https://connor.container.se.lab.emc.com
    deploy:
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:connor.container.se.lab.emc.com"
        - "traefik.port=3000"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

configs:
  isi_data_config:
    file: ./isi_data_insights_d.cfg
  grafana_dashboards:
    file: ./dashboard_default.yml
  grafana_datasource:
    file: ./datasource_default.yml

networks:
  traefik-net:
    external: true
